# ----------------------------------------------------------------------------------------------------
# Pipeline used by the azd command
# ----------------------------------------------------------------------------------------------------
name: elevator-dispatch-azd

infra:
  provider: bicep
  path: infra
  module: azd-main

hooks:
  preup:
    shell: pwsh
    run: ./infra/scripts/ensure-azd-env.ps1
    interactive: true

pipeline:
  provider: github

services:
  web:
    project: ./src/ElevatorApi/
    language: csharp
    host: appservice
